name = 'not-much'
license = 'MIT'
licenselink = 'https://github.com/imgios/not-much/LICENSE'
description = 'A minimal blog theme for Hugo'

homepage = 'https://github.com/imgios/not-much'

demosite = 'https://imgios.github.io/not-much/'

tags = ['blog', 'website']

features = ['blog']

[author]
  name = 'Giosuè Sulipano'
  homepage = 'https://giosuesulipano.it'