# The following line is needed
# when running the example site
# from a subdir of the theme
themesDir = "../../"

theme = "not-much"

title = "not-much demo"
languageCode = "en-us"
baseURL = "https://example.org/"