# The following line is needed
# when running the example site
# from a subdir of the theme
themesDir = "../../"

title = "not-much demo"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "© {year}"

[markup]
  [markup.highlight]
    style = 'dracula'

[params]

# Navigation
[[menu.main]]
  identifier = "home"
  name = "home"
  title = "Home"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"

[[menu.main]]
  identifier = "github"
  name = "github"
  title = "GitHub"
  url = "https://github.com/imgios"